devices([
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone SE",
  "iPhone XS",
  "iPhone XS Max",
  "iPad Pro (12.9-inch)",
  "iPad Pro (10.5-inch)",
  "iPad Pro (9.7-inch)"
])

languages([
  "en-US",
  "de-DE"
])

scheme("StudAppSnapshots")

clear_previous_screenshots(true)
